
Assembly:
    Company : "Heartysoft Solutions Limited"
    Version : "0.0.1"
    PreRelease: "alpha" #empty for release version. Informational version (and so nuget) will be Version-PrePrelease / Version
